"""create product table

Revision ID: 6dc3703942d6
Revises: 230df5a2ce09
Create Date: 2025-09-20 11:41:05.419494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc3703942d6'
down_revision: Union[str, Sequence[str], None] = '230df5a2ce09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('produ_id', sa.Integer(), nullable=False),
    sa.Column('produ_name', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('produ_id'),
    sa.UniqueConstraint('price')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
