services:
  posgres_db:
    container_name: postgres_container2
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 10s
      retries: 5 
      start_period: 30s

  pgadmin4:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      posgres_db:
        condition: service_healthy

  fastapi_app:
    container_name: fastapi_container2
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/testing_in_fastapi
    depends_on:
      posgres_db:
        condition: service_healthy

volumes:
  postgres_data: