[project]
name = "server-sent-event"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "aiohttp>=3.13.1",
    "fastapi[standard]>=0.120.0",
    "pathlib>=1.0.1",
    "requests>=2.32.5",
]
